export const HOME_GET_LEARNING_OBJECT_LIST_BEGIN = 'HOME_GET_LEARNING_OBJECT_LIST_BEGIN';
export const HOME_GET_LEARNING_OBJECT_LIST_SUCCESS = 'HOME_GET_LEARNING_OBJECT_LIST_SUCCESS';
export const HOME_GET_LEARNING_OBJECT_LIST_FAILURE = 'HOME_GET_LEARNING_OBJECT_LIST_FAILURE';
export const HOME_GET_LEARNING_OBJECT_LIST_DISMISS_ERROR = 'HOME_GET_LEARNING_OBJECT_LIST_DISMISS_ERROR';
export const HOME_GO_TO_PREVIOUS_PAGE = 'HOME_GO_TO_PREVIOUS_PAGE';
export const HOME_GO_TO_NEXT_PAGE = 'HOME_GO_TO_NEXT_PAGE';
export const HOME_SEARCH_TEXT = 'HOME_SEARCH_TEXT';
